"""Alter keys in User

Revision ID: 18112c8f81af
Revises: a549f75f21ca
Create Date: 2025-02-19 03:43:24.562269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18112c8f81af'
down_revision: Union[str, None] = 'a549f75f21ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aihelper_user', 'fernet_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('aihelper_user', 'session_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aihelper_user', 'session_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('aihelper_user', 'fernet_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
