"""Alter phone_number unique

Revision ID: 2c3907fcd591
Revises: 18112c8f81af
Create Date: 2025-02-19 03:54:48.435608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c3907fcd591'
down_revision: Union[str, None] = '18112c8f81af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'aihelper_user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aihelper_user', type_='unique')
    # ### end Alembic commands ###
