"""Add a password column

Revision ID: a549f75f21ca
Revises: b813ac97cac5
Create Date: 2025-02-19 02:54:36.608326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a549f75f21ca'
down_revision: Union[str, None] = 'b813ac97cac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aihelper_user', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aihelper_user', 'password')
    # ### end Alembic commands ###
