"""Add a fernet_key to User model

Revision ID: b813ac97cac5
Revises: fb2467dfd5c5
Create Date: 2025-02-19 02:03:45.053472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b813ac97cac5'
down_revision: Union[str, None] = 'fb2467dfd5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aihelper_user', sa.Column('fernet_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aihelper_user', 'fernet_key')
    # ### end Alembic commands ###
