"""Alter Chat models

Revision ID: cf73f2d1f70e
Revises: 2c3907fcd591
Create Date: 2025-02-19 06:40:40.219271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf73f2d1f70e'
down_revision: Union[str, None] = '2c3907fcd591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_aihelper_image_chat_answer', table_name='aihelper_image')
    op.drop_constraint('aihelper_image_chat_answer_fkey', 'aihelper_image', type_='foreignkey')
    op.drop_column('aihelper_image', 'chat_answer')
    op.drop_index('ix_aihelper_chat_answer_chat', table_name='aihelper_chat_answer')
    op.drop_table('aihelper_chat_answer')
    op.add_column('aihelper_chat_message', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('aihelper_chat_message', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('aihelper_chat_message', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aihelper_chat_answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('chat', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['aihelper_chat.id'], name='aihelper_chat_answer_chat_fkey'),
    sa.PrimaryKeyConstraint('id', name='aihelper_chat_answer_pkey')
    )
    op.create_index('ix_aihelper_chat_answer_chat', 'aihelper_chat_answer', ['chat'], unique=False)
    op.add_column('aihelper_image', sa.Column('chat_answer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('aihelper_image_chat_answer_fkey', 'aihelper_image', 'aihelper_chat_answer', ['chat_answer'], ['id'])
    op.create_index('ix_aihelper_image_chat_answer', 'aihelper_image', ['chat_answer'], unique=False)
    op.add_column('aihelper_chat_message', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('aihelper_chat_message', 'content')
    op.drop_column('aihelper_chat_message', 'role')
    # ### end Alembic commands ###
