"""Init models

Revision ID: fb2467dfd5c5
Revises: 
Create Date: 2025-02-19 01:52:17.060674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb2467dfd5c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aihelper_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aihelper_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['aihelper_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aihelper_chat_user_id'), 'aihelper_chat', ['user_id'], unique=False)
    op.create_table('aihelper_chat_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['aihelper_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aihelper_chat_answer_chat'), 'aihelper_chat_answer', ['chat'], unique=False)
    op.create_table('aihelper_chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['aihelper_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aihelper_chat_message_chat'), 'aihelper_chat_message', ['chat'], unique=False)
    op.create_table('aihelper_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chat_message', sa.Integer(), nullable=True),
    sa.Column('chat_answer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_answer'], ['aihelper_chat_answer.id'], ),
    sa.ForeignKeyConstraint(['chat_message'], ['aihelper_chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aihelper_image_chat_answer'), 'aihelper_image', ['chat_answer'], unique=False)
    op.create_index(op.f('ix_aihelper_image_chat_message'), 'aihelper_image', ['chat_message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aihelper_image_chat_message'), table_name='aihelper_image')
    op.drop_index(op.f('ix_aihelper_image_chat_answer'), table_name='aihelper_image')
    op.drop_table('aihelper_image')
    op.drop_index(op.f('ix_aihelper_chat_message_chat'), table_name='aihelper_chat_message')
    op.drop_table('aihelper_chat_message')
    op.drop_index(op.f('ix_aihelper_chat_answer_chat'), table_name='aihelper_chat_answer')
    op.drop_table('aihelper_chat_answer')
    op.drop_index(op.f('ix_aihelper_chat_user_id'), table_name='aihelper_chat')
    op.drop_table('aihelper_chat')
    op.drop_table('aihelper_user')
    # ### end Alembic commands ###
